<?php

namespace App\Console\Commands;

use Database\Seeders\DemoDataCleanupSeeder;
use Illuminate\Console\Command;

class DemoDataClear extends Command
{
    protected $signature = 'demo-data:clear';

    protected $description = 'Remove only records generated by DemoDataSeeder';

    public function handle(): int
    {
        $this->call(DemoDataCleanupSeeder::class);
        $this->info('DEMO data cleanup completed; protected tables were not modified.');

        return self::SUCCESS;
    }
}
