@extends('layouts.admin')

@section('title', 'eDonate - Blood Requests')
@section('admin_page_class', 'admin-blood-requests-page')
@section('header_title', 'Blood Requests')
@section('header_subtitle', 'Create and manage facility blood and replacement donor requests')

@section('header_actions')
<button class="btn btn-danger" type="button" id="createRequestButton">Create Request</button>
@endsection

@section('main_content')
<main class="request-content">
    <section class="request-summary" aria-label="Blood request summary">
        <div class="request-stat"><span>Pending Review</span><strong id="requestPendingReview">-</strong></div>
        <div class="request-stat"><span>Open Requests</span><strong id="requestOpen">-</strong></div>
        <div class="request-stat"><span>Emergency Requests</span><strong id="requestEmergency">-</strong></div>
        <div class="request-stat"><span>Fulfilled</span><strong id="requestFulfilled">-</strong></div>
        <div class="request-stat"><span>Cancelled</span><strong id="requestCancelled">-</strong></div>
    </section>
    <section class="request-panel">
        <div class="request-toolbar">
            <div><label for="requestSearch">Search</label><input class="form-control" id="requestSearch" type="search" maxlength="150" placeholder="Reference, requester, facility, or email"></div>
            <div><label for="requestStatus">Status</label><select class="form-select" id="requestStatus"><option value="">All</option><option value="pending_review">Pending review</option><option value="draft">Draft</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="fulfilled">Fulfilled</option><option value="cancelled">Cancelled</option><option value="rejected">Rejected</option><option value="expired">Expired</option></select></div>
            <div><label for="requestUrgency">Urgency</label><select class="form-select" id="requestUrgency"><option value="">All</option><option value="normal">Normal</option><option value="urgent">Urgent</option><option value="emergency">Emergency</option></select></div>
            <div><label for="requestBloodType">Blood type</label><select class="form-select" id="requestBloodType"><option value="">All</option>@foreach($bloodTypes as $bloodType)<option value="{{ $bloodType->blood_type_id }}">{{ $bloodType->blood_type }}</option>@endforeach</select></div>
            <div><label for="requestSource">Source</label><select class="form-select" id="requestSource"><option value="">All sources</option><option value="app">Donor app</option><option value="admin">Admin</option></select></div>
            <button class="btn btn-outline-secondary" id="requestClear" type="button">Clear</button>
        </div>
        <div class="request-table-wrap" role="region" aria-label="Blood requests table, scroll horizontally if needed" tabindex="0">
            <table class="table table-hover request-table"><thead><tr><th>Reference</th><th>Requester</th><th>Facility</th><th>Type</th><th>Blood Type</th><th>Required</th><th>Notified</th><th>Interested</th><th>Urgency</th><th>Status</th><th>Source</th><th>Submitted</th><th>Actions</th></tr></thead><tbody id="requestRows"><tr><td colspan="13" class="text-center text-muted py-4">Loading...</td></tr></tbody></table>
        </div>
        <div class="admin-pagination admin-pagination--js" aria-label="Table pagination">
            <span class="admin-pagination__info" id="requestMeta">Showing 0 to 0 of 0 entries</span>
            <nav class="admin-pagination__links" id="requestPaginationLinks" aria-label="Pagination links"></nav>
        </div>
    </section>
</main>

<div class="modal fade" id="requestModal" tabindex="-1" aria-labelledby="requestModalTitle" aria-hidden="true"><div class="modal-dialog modal-lg"><form class="modal-content" id="requestForm"><input type="hidden" name="submission_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><div class="modal-header"><h2 class="modal-title fs-5" id="requestModalTitle">Create Blood Request</h2><button class="btn-close" data-bs-dismiss="modal" type="button" aria-label="Close"></button></div><div class="modal-body"><div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="blood_requests-facility_id">Facility</label><select id="blood_requests-facility_id" class="form-select" name="facility_id" required>@foreach($facilities as $facility)<option value="{{ $facility->facility_id }}">{{ $facility->facility_name }}</option>@endforeach</select><div class="invalid-feedback" data-validation-for="facility_id"></div></div>
    <div class="col-md-6"><label class="form-label" for="blood_requests-request_type">Request type</label><select id="blood_requests-request_type" class="form-select" name="request_type" required><option value="replacement_donor">Replacement Donor</option><option value="blood_request">Blood Request</option></select><div class="invalid-feedback" data-validation-for="request_type"></div></div>
    <div class="col-md-4"><label class="form-label" for="blood_requests-needed_blood_type_id">Needed blood type</label><select id="blood_requests-needed_blood_type_id" class="form-select" name="needed_blood_type_id" required>@foreach($bloodTypes as $bloodType)<option value="{{ $bloodType->blood_type_id }}">{{ $bloodType->blood_type }}</option>@endforeach</select><div class="invalid-feedback" data-validation-for="needed_blood_type_id"></div></div>
    <div class="col-md-4"><label class="form-label" for="blood_requests-required_donors">Required donors</label><input id="blood_requests-required_donors" class="form-control" name="required_donors" type="number" min="1" max="1000" value="1" required><div class="invalid-feedback" data-validation-for="required_donors"></div></div>
    <div class="col-md-4"><label class="form-label" for="blood_requests-specific_match_required">Specific match required</label><input id="blood_requests-specific_match_required" class="form-control" name="specific_match_required" type="number" min="0" max="1000" value="1"><div class="invalid-feedback" data-validation-for="specific_match_required"></div></div>
    <div class="col-md-4"><label class="form-label" for="blood_requests-allow_other_blood_types">Allow other blood types</label><select id="blood_requests-allow_other_blood_types" class="form-select" name="allow_other_blood_types"><option value="1">Yes</option><option value="0">No</option></select><div class="invalid-feedback" data-validation-for="allow_other_blood_types"></div></div>
    <div class="col-md-4"><label class="form-label" for="blood_requests-urgency">Urgency</label><select id="blood_requests-urgency" class="form-select" name="urgency"><option value="normal">Normal</option><option value="urgent">Urgent</option><option value="emergency">Emergency</option></select><div class="invalid-feedback" data-validation-for="urgency"></div></div>
    <div class="col-md-4"><label class="form-label" for="blood_requests-expires_at">Expires at</label><input id="blood_requests-expires_at" class="form-control" name="expires_at" type="datetime-local"><div class="invalid-feedback" data-validation-for="expires_at"></div></div>
    <div class="col-12"><label class="form-label" for="blood_requests-notes">Notes</label><textarea id="blood_requests-notes" class="form-control" name="notes" rows="3" maxlength="2000"></textarea><div class="invalid-feedback" data-validation-for="notes"></div></div>
    <div class="col-12"><div class="alert alert-danger d-none mb-0" id="requestErrors" role="alert" aria-live="polite"></div></div>
</div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal" type="button">Cancel</button><button class="btn btn-danger" type="submit" id="requestSave">Save Request</button></div></form></div></div>
@endsection

@push('admin_scripts')
<script>
(function(){'use strict';
const urls={data:@json(route('admin.blood-requests.data')),store:@json(route('admin.blood-requests.store'))},csrf=document.querySelector('meta[name="csrf-token"]').content,rows=document.getElementById('requestRows'),paginationLinks=document.getElementById('requestPaginationLinks'),requestMeta=document.getElementById('requestMeta');let page=1,timer=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),head=v=>String(v??'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
async function req(url,opt={}){const res=await fetch(url,{...opt,headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest','X-CSRF-TOKEN':csrf,'Content-Type':'application/json',...(opt.headers||{})}}),data=await res.json().catch(()=>({}));if(!res.ok){const error=new Error(data.message||'The request could not be completed. Please try again.');error.status=res.status;error.errors=data.errors||{};throw error}return data}
function params(){const q=new URLSearchParams({page});[['search','requestSearch'],['status','requestStatus'],['urgency','requestUrgency'],['blood_type_id','requestBloodType'],['source','requestSource']].forEach(([k,id])=>{const v=document.getElementById(id).value.trim();if(v)q.set(k,v)});return q}
async function load(){rows.innerHTML='<tr><td colspan="13" class="text-center text-muted py-4">Loading...</td></tr>';try{const data=await req(`${urls.data}?${params()}`),s=data.summary||{},meta=data.meta||{};page=Number(meta.current_page||page);document.getElementById('requestPendingReview').textContent=s.pending_review??0;document.getElementById('requestOpen').textContent=s.open??0;document.getElementById('requestEmergency').textContent=s.emergency??0;document.getElementById('requestFulfilled').textContent=s.fulfilled??0;document.getElementById('requestCancelled').textContent=s.cancelled??0;if(window.eDonateAdminPagination)window.eDonateAdminPagination.render(paginationLinks,meta,null,{infoElement:requestMeta});rows.innerHTML=(data.data||[]).length?(data.data||[]).map(r=>`<tr><td><strong>${esc(r.request_reference)}</strong></td><td>${esc(r.requester_name)}${r.requester_email?`<br><small>${esc(r.requester_email)}</small>`:''}${r.requester_contact?`<br><small>${esc(r.requester_contact)}</small>`:''}</td><td>${esc(r.facility_name)}</td><td>${esc(head(r.request_type))}</td><td>${esc(r.needed_blood_type)}</td><td>${esc(r.required_donors)}<br><small class="text-muted">${esc(r.specific_match_required)} exact</small></td><td>${esc(r.notified_count)}</td><td>${esc(r.interested_count)}</td><td><span class="request-badge request-badge--${esc(r.urgency)}">${esc(head(r.urgency))}</span></td><td><span class="request-badge request-badge--${esc(r.status)}">${esc(head(r.status))}</span></td><td>${esc(head(r.request_source))}</td><td>${r.created_at?esc(new Date(r.created_at).toLocaleString()):''}</td><td><a class="btn btn-sm btn-outline-danger" href="${esc(r.show_url)}">View</a></td></tr>`).join(''):'<tr><td colspan="13" class="text-center text-muted py-4">No blood requests found.</td></tr>'}catch(e){rows.innerHTML='<tr><td colspan="13" class="text-center text-danger py-4">Could not load blood requests.</td></tr>';if(requestMeta)requestMeta.textContent='Showing 0 to 0 of 0 entries';if(paginationLinks)paginationLinks.innerHTML=''}}
paginationLinks.addEventListener('click',(event)=>{const button=event.target.closest('button[data-page]');if(!button)return;page=Number(button.dataset.page||1);load();});['requestSearch','requestStatus','requestUrgency','requestBloodType','requestSource'].forEach(id=>document.getElementById(id).addEventListener(id==='requestSearch'?'input':'change',()=>{clearTimeout(timer);timer=setTimeout(()=>{page=1;load()},250)}));document.getElementById('requestClear').onclick=()=>{['requestSearch','requestStatus','requestUrgency','requestBloodType','requestSource'].forEach(id=>document.getElementById(id).value='');page=1;load()};
const modalElement=document.getElementById('requestModal'),form=document.getElementById('requestForm'),errors=document.getElementById('requestErrors'),saveButton=document.getElementById('requestSave');let modal=null,saving=false;const getModal=()=>{if(!modal&&modalElement&&window.bootstrap&&window.bootstrap.Modal)modal=window.bootstrap.Modal.getOrCreateInstance(modalElement);return modal;};
function makeSubmissionKey(){const bytes=new Uint8Array(16);window.crypto.getRandomValues(bytes);bytes[6]=(bytes[6]&0x0f)|0x40;bytes[8]=(bytes[8]&0x3f)|0x80;const hex=Array.from(bytes,value=>value.toString(16).padStart(2,'0')).join('');return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`}
function clearValidation(){form.querySelectorAll('.is-invalid').forEach(field=>field.classList.remove('is-invalid'));form.querySelectorAll('[data-validation-for]').forEach(feedback=>feedback.textContent='');errors.textContent='';errors.classList.add('d-none')}
function showErrors(error){clearValidation();const fieldErrors=error.errors||{};let fieldCount=0;Object.entries(fieldErrors).forEach(([name,messages])=>{const field=form.elements.namedItem(name),feedback=form.querySelector(`[data-validation-for="${CSS.escape(name)}"]`);if(!field)return;field.classList.add('is-invalid');if(feedback)feedback.textContent=Array.isArray(messages)?messages[0]:String(messages);fieldCount++});errors.textContent=fieldCount?'Please correct the highlighted fields.':(error.message||'We could not save this blood request. Please try again.');errors.classList.remove('d-none')}
form.querySelectorAll('input,select,textarea').forEach(field=>field.addEventListener('input',()=>{field.classList.remove('is-invalid');const feedback=form.querySelector(`[data-validation-for="${CSS.escape(field.name)}"]`);if(feedback)feedback.textContent=''}));
document.getElementById('createRequestButton').onclick=()=>{if(saving)return;form.reset();clearValidation();form.elements.namedItem('submission_key').value=makeSubmissionKey();const modalInstance=getModal();if(modalInstance)modalInstance.show()};
form.onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;saveButton.disabled=true;const payload=Object.fromEntries(new FormData(form));payload.allow_other_blood_types=payload.allow_other_blood_types==='1';if(payload.expires_at){const localExpiry=new Date(payload.expires_at);if(Number.isNaN(localExpiry.getTime())){showErrors({errors:{expires_at:['Enter a valid expiration date and time.']}});saving=false;saveButton.disabled=false;return}payload.expires_at=localExpiry.toISOString()}else payload.expires_at=null;try{await req(urls.store,{method:'POST',body:JSON.stringify(payload)});getModal()?.hide();load()}catch(err){showErrors(err)}finally{saving=false;saveButton.disabled=false}};load();
}());
</script>
@endpush
